updated README, updated bash/exports, removed unused functions in bash/functions, updated lfrc, updated vimrc

diff --git a/lf/lfrc b/lf/lfrc
--- a/lf/lfrc
+++ b/lf/lfrc
@@ -1,6 +1,7 @@
 set shell bash
 set shellopts '-eu'
 set ifs "\n"
+
 set icons
 set hidden
 set drawbox
@@ -14,6 +15,9 @@ set sortby natural
 set ratios '1:2:3'
 set period 1
 set relativenumber
+set preview
+
+set previewer ~/.config/lf/preview
 
 set cursorpreviewfmt ""
 set cursorparentfmt "\033[7m"
@@ -23,12 +27,13 @@ set numberfmt "\033[38;5;8m"
 #### mappings
 
 # remove defaults
-map y
-map p
 map d
-map r
 map f
+map F
+map p
+map r
 map w
+map y
 map sa
 map sc
 map se
@@ -65,13 +70,21 @@ map S edit-with-sudo
 map o &mimeopen $f
 map O push :openwith<space>
 
+map ff filter
+
 # fuzzy-find a file
 map fF $lf -remote "send $id select $(fzf)"
-map ff filter
+
+# fuzzy search
+map <c-f> :fzf_search
+
+# jump dirs
+map F :fzf_jump
+
+map xx extract
 
 # enter name and compress to name.zip
 map xX push :zip<space>
-map xx extract
 
 # jump-dir w\ zoxide
 map zz push :z<space>
@@ -91,11 +104,27 @@ map g? $lf -doc | less
 # put lf on the background
 map <c-z> $ kill -STOP $PPID
 
-# beyond compare selected files/directories
-map = &bcompare $fx
-
 
 #### commands
+
+# command autocompletion
+cmap <enter> &{{
+    if [ "$lf_mode" = command ]; then
+        lf -remote "send $id complete-cmd"
+    else
+        lf -remote "send $id cmd-enter"
+    fi
+}}
+
+cmd complete-cmd :{{
+    # position cursor at the end of the first word
+    cmd-home
+    cmd-word
+
+    # perform tab completion before running the command
+    cmd-complete
+    cmd-enter
+}}
 
 # edit-with-sudo
 cmd edit-with-sudo ${{
@@ -151,45 +180,80 @@ cmd new-folder-with-selection ${{
 
 # compress current file or selected files with zip
 cmd zip ${{
-    set -f
-    mkdir $1
-    cp -r $fx $1
-    zip -r $1.zip $1
-    rm -rf $1
+	if hash zip 2>/dev/null; then
+		set -f
+		mkdir $1
+		cp -r $fx $1
+		zip -r $1.zip $1
+		rm -rf $1
+	fi
 }}
 
 # extract compressed files
 cmd extract ${{
-    set -f
-        case $f in
-        *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf $f;;
-        *.tar.gz|*.tgz) tar xzvf $f;;
-        *.tar.xz|*.txz) tar xJvf $f;;
-        *.zip) unzip -O gbk $f;;
-        *.rar) unrar x $f;;
-        *.7z) 7z x $f;;
-    esac
+	set -f
+		case $f in
+		*.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf $f;;
+		*.tar.gz|*.tgz) tar xzvf $f;;
+		*.tar.xz|*.txz) tar xJvf $f;;
+		*.zip) unzip -O gbk $f;;
+		*.rar) unrar x $f;;
+		*.7z) 7z x $f;;
+	esac
 }}
 
 # cd into recent directories w\ zoxide
 cmd z ${{
-  set +u
-  dest=''
-  prefix=''
-  if hash zoxide 2>/dev/null; then
-    dest="$(zoxide query "$@")"
-  fi
+	if hash zoxide 2>/dev/null; then
+		set +u
+		dest=''
+		prefix=''
+		if hash zoxide 2>/dev/null; then
+			dest="$(zoxide query "$@")"
+		fi
 
-  if test -n "${dest}"; then
-    lf -remote "send $id cd '${dest}'"
-  else
-    lf -remote "send $id echo 'Invalid directory ${dest}'"
-  fi
+		if test -n "${dest}"; then
+			lf -remote "send $id cd '${dest}'"
+		else
+			lf -remote "send $id echo 'Invalid directory ${dest}'"
+		fi
+	fi
 }}
 
 cmd fzf_z ${{
-  sel="$(zoxide query -l | fzf +s)"
-  [ -d "$sel" ] && lf -remote "send $id cd \"$sel\""
+	if hash zoxide 2>/dev/null; then
+		sel="$(zoxide query -l | fzf +s)"
+		[ -d "$sel" ] && lf -remote "send $id cd \"$sel\""
+	fi
+}}
+
+cmd fzf_jump ${{
+	res="$(find . -maxdepth 1 | fzf --reverse --header='Jump to location')"
+	if [ -n "$res" ]; then
+		if [ -d "$res" ]; then
+			cmd="cd"
+		else
+			cmd="select"
+		fi
+		res="$(printf '%s' "$res" | sed 's/\\/\\\\/g;s/"/\\"/g')"
+		lf -remote "send $id $cmd \"$res\""
+	fi
+}}
+
+cmd fzf_search ${{
+	if hash fzf 2>/dev/null; then
+		cmd="rg --column --line-number --no-heading --color=always --smart-case"
+		fzf --ansi --disabled --layout=reverse --header="Search in files" --delimiter=: \
+				--bind="start:reload([ -n {q} ] && $cmd -- {q} || true)" \
+				--bind="change:reload([ -n {q} ] && $cmd -- {q} || true)" \
+				--bind='enter:become(lf -remote "send $id select \"$(printf "%s" {1} | sed '\''s/\\/\\\\/g;s/"/\\"/g'\'')\"")' \
+				#--preview='cat -- {1}' # Use your favorite previewer here (bat, source-highlight, etc.), for example:
+				#--preview-window='+{2}-/2' \
+				#--preview='bat --color=always --highlight-line={2} -- {1}'
+				# Alternatively you can even use the same previewer you've configured for lf
+				--preview='~/.config/lf/clean; ~/.config/lf/preview -- {1}'
+				#--preview='~/.config/lf/clean; ~/.config/lf/preview {1} "$FZF_PREVIEW_COLUMNS" "$FZF_PREVIEW_LINES" "$FZF_PREVIEW_LEFT" "$FZF_PREVIEW_TOP"'
+	fi
 }}
 
 # helper to cd to curr dir on quit
@@ -205,10 +269,9 @@ cmd reload-conf ${{
 
 #### prompt
 
-set promptfmt "
-\033[38;5;8m\033[48;5;236m %u@%h \033[38;5;236m\033[48;5;234m
-\033[34;40;1m\033[48;5;234m %w/%f \033[0m\033[38;5;234m\033[0m
-"
+set promptfmt
+" \033[38;5;8m\033[48;5;236m %u@%h \033[38;5;236m\033[48;5;234m \033[34;40;1m\033[48;5;234m %w/%f \033[0m\033[38;5;234m\033[0m"
+
 # git branch prompt
 cmd on-cd &{{
     # display git repository status in your prompt
@@ -223,4 +286,4 @@ cmd on-cd &{{
     lf -remote "send $id set promptfmt \"$fmt\""
 }}
 
-# vim: set ft=conf :
+# vim: set ts=2 sw=2 tw=80 noet :
